const ADD_TO_CART = "ADD_TO_CART" 
const REMOVE_FROM_CART = "REMOVE_FROM_CART"
const CHECKOUT = "CHECKOUT"

const POSTSTART ="POSTSTART"
const POSTSUCCESS= "POSTSUCCESS"
const POSTFAILURE="POSTFAILURE"

export {ADD_TO_CART,REMOVE_FROM_CART,CHECKOUT,POSTSTART,POSTSUCCESS,POSTFAILURE}